apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  template:
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values-dev.yaml