apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      source:
        helm:
          valueFiles:
            - values-dev.yaml