apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/polinchw/cluster-addons.git
      revision: HEAD
      directories:
      - path: addons/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/polinchw/cluster-addons.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values-prod-east.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true